# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_code.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(594, 406)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 291))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.InName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.InName.setObjectName("InName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.InName)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.InId = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.InId.setObjectName("InId")
        self.horizontalLayout.addWidget(self.InId)
        self.btnFindId = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnFindId.setObjectName("btnFindId")
        self.horizontalLayout.addWidget(self.btnFindId)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lblChkId = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblChkId.sizePolicy().hasHeightForWidth())
        self.lblChkId.setSizePolicy(sizePolicy)
        self.lblChkId.setObjectName("lblChkId")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lblChkId)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.spAge = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spAge.setProperty("value", 19)
        self.spAge.setObjectName("spAge")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spAge)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.InPNum = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.InPNum.setObjectName("InPNum")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.InPNum)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.InPNum2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.InPNum2.setObjectName("InPNum2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.InPNum2)
        self.btnOk = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnOk.setObjectName("btnOk")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.btnOk)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "이름 :"))
        self.label_2.setText(_translate("Form", "ID :"))
        self.btnFindId.setText(_translate("Form", "중복검사"))
        self.lblChkId.setText(_translate("Form", "ID 중복검사를 진행해 주세요"))
        self.label_5.setText(_translate("Form", "나이 :"))
        self.label_11.setText(_translate("Form", "연락처 :"))
        self.label_12.setText(_translate("Form", "보호자연락처 :"))
        self.btnOk.setText(_translate("Form", "확인"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
