# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_wnd_intel.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(897, 711)
        MainWindow.setMinimumSize(QtCore.QSize(897, 711))
        MainWindow.setMaximumSize(QtCore.QSize(897, 711))
        MainWindow.setMouseTracking(True)
        MainWindow.setTabletTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableLib = QtWidgets.QTableView(self.centralwidget)
        self.tableLib.setGeometry(QtCore.QRect(30, 130, 831, 331))
        self.tableLib.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableLib.setProperty("showDropIndicator", False)
        self.tableLib.setDragEnabled(True)
        self.tableLib.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableLib.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.tableLib.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableLib.setObjectName("tableLib")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 20, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableConst = QtWidgets.QTableView(self.centralwidget)
        self.tableConst.setGeometry(QtCore.QRect(30, 530, 451, 131))
        self.tableConst.setObjectName("tableConst")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(29, 70, 411, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.file_name = QtWidgets.QLabel(self.layoutWidget)
        self.file_name.setFrameShape(QtWidgets.QFrame.Panel)
        self.file_name.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.file_name.setText("")
        self.file_name.setObjectName("file_name")
        self.gridLayout.addWidget(self.file_name, 2, 0, 1, 1)
        self.btnGraph = QtWidgets.QPushButton(self.centralwidget)
        self.btnGraph.setGeometry(QtCore.QRect(760, 540, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnGraph.setFont(font)
        self.btnGraph.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btnGraph.setObjectName("btnGraph")
        self.btnExcel = QtWidgets.QPushButton(self.centralwidget)
        self.btnExcel.setGeometry(QtCore.QRect(760, 580, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnExcel.setFont(font)
        self.btnExcel.setStyleSheet("\n"
"background-color: rgb(198, 180, 255);")
        self.btnExcel.setObjectName("btnExcel")
        self.fileLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fileLineEdit.setGeometry(QtCore.QRect(600, 590, 151, 21))
        self.fileLineEdit.setObjectName("fileLineEdit")
        self.layoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(30, 470, 731, 47))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.prog_filepre = QtWidgets.QLabel(self.layoutWidget_4)
        self.prog_filepre.setFrameShape(QtWidgets.QFrame.Panel)
        self.prog_filepre.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.prog_filepre.setText("")
        self.prog_filepre.setObjectName("prog_filepre")
        self.gridLayout_3.addWidget(self.prog_filepre, 1, 3, 1, 1)
        self.prog_load = QtWidgets.QLabel(self.layoutWidget_4)
        self.prog_load.setFrameShape(QtWidgets.QFrame.Panel)
        self.prog_load.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.prog_load.setText("")
        self.prog_load.setObjectName("prog_load")
        self.gridLayout_3.addWidget(self.prog_load, 1, 0, 1, 1)
        self.prog_conv = QtWidgets.QLabel(self.layoutWidget_4)
        self.prog_conv.setFrameShape(QtWidgets.QFrame.Panel)
        self.prog_conv.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.prog_conv.setText("")
        self.prog_conv.setObjectName("prog_conv")
        self.gridLayout_3.addWidget(self.prog_conv, 1, 2, 1, 1)
        self.prog_disp = QtWidgets.QLabel(self.layoutWidget_4)
        self.prog_disp.setFrameShape(QtWidgets.QFrame.Panel)
        self.prog_disp.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.prog_disp.setText("")
        self.prog_disp.setObjectName("prog_disp")
        self.gridLayout_3.addWidget(self.prog_disp, 1, 1, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(470, 70, 391, 51))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lot_no = QtWidgets.QLabel(self.layoutWidget_2)
        self.lot_no.setFrameShape(QtWidgets.QFrame.Panel)
        self.lot_no.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lot_no.setText("")
        self.lot_no.setObjectName("lot_no")
        self.gridLayout_2.addWidget(self.lot_no, 2, 1, 1, 1)
        self.part_name = QtWidgets.QLabel(self.layoutWidget_2)
        self.part_name.setFrameShape(QtWidgets.QFrame.Panel)
        self.part_name.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.part_name.setText("")
        self.part_name.setObjectName("part_name")
        self.gridLayout_2.addWidget(self.part_name, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 897, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu_F = QtWidgets.QMenu(self.menuBar)
        self.menu_F.setObjectName("menu_F")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen_2 = QtWidgets.QAction(MainWindow)
        self.actionOpen_2.setObjectName("actionOpen_2")
        self.menu_F.addAction(self.actionOpen_2)
        self.menuBar.addAction(self.menu_F.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Intel 데이터 자동 변환 프로그램"))
        self.label_3.setText(_translate("MainWindow", "화일명"))
        self.btnGraph.setText(_translate("MainWindow", "그래프"))
        self.btnExcel.setText(_translate("MainWindow", "결과저장"))
        self.fileLineEdit.setPlaceholderText(_translate("MainWindow", "저장할 파일명 입력"))
        self.label_8.setText(_translate("MainWindow", "File preperation"))
        self.label_10.setText(_translate("MainWindow", "Output Data Conversion"))
        self.label_7.setText(_translate("MainWindow", "Display Loaded Data"))
        self.label_9.setText(_translate("MainWindow", "Data Loading"))
        self.label_13.setText(_translate("MainWindow", "Lot"))
        self.label_12.setText(_translate("MainWindow", "기종명"))
        self.menu_F.setTitle(_translate("MainWindow", "파일 (F)"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen_2.setText(_translate("MainWindow", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

